name: CI

on:
  push:
  workflow_dispatch:
  pull_request:


jobs:
  test:
    name: "Test git-bug"
    runs-on: windows-latest
    strategy:
      matrix:
        environment: [broken, fixed]
    steps:
       - uses: actions/checkout@v4
       - uses: prefix-dev/setup-pixi@v0.8.3
         with:
           environments: ${{ matrix.environment }}
       - run: mkdir ..\outside_project
       - run: pixi run git init ..\outside_project
